# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'A1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for A1
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'BrightFutures', :git => 'https://github.com/Thomvis/BrightFutures.git', :tag => '6.0.1'
	pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :tag => 'v0.11.1'
	
end
